Creating a Welcome page
Infinical/library_app pull request #1
Opened 2019-03-14 12:33 UTC by Infinical

2019-03-14 14:21 UTC, LindaKadz submitted a review, later dismissed
Remove the user stories if you are not using them on this branch

2019-03-15 06:53 UTC, Infinical commented
![Screenshot from 2019-03-15 12-51-29](https://user-images.githubusercontent.com/16985576/54413813-1a6a5f00-4708-11e9-94db-fb25c62e9867.png)
![Screenshot from 2019-03-15 12-51-59](https://user-images.githubusercontent.com/16985576/54413814-1a6a5f00-4708-11e9-8bc5-d510e450ae7f.png)

2019-03-15 06:53 UTC, Infinical commented
![Screenshot from 2019-03-15 12-51-29](https://user-images.githubusercontent.com/16985576/54413839-37069700-4708-11e9-86d8-227d65081d94.png)
![Screenshot from 2019-03-15 12-51-59](https://user-images.githubusercontent.com/16985576/54413840-37069700-4708-11e9-9fa7-33925a1e7ee2.png)

2019-03-15 06:54 UTC, Infinical commented
![Screenshot from 2019-03-15 12-51-29](https://user-images.githubusercontent.com/16985576/54413861-4b4a9400-4708-11e9-9acb-cf7af6c0e9f3.png)

2019-03-15 06:54 UTC, Infinical commented
![Screenshot from 2019-03-15 12-51-59](https://user-images.githubusercontent.com/16985576/54413873-5998b000-4708-11e9-9ef7-15950526bd72.png)

2019-03-15 07:22 UTC, sigu requested changes

2019-03-15 07:22 UTC, sigu commented on features/list_books.feature
> +
Remove this space, the description is part of the feature

2019-03-15 07:22 UTC, sigu commented on test/controllers/welcome_controller_test.rb
> +require 'test_helper'
We do not need this controller tests. Controller are covered by cucumber tests ( Feature tests)


This does not mean that controller tests are not important, it depends on the organisation. Some prefer and insist of these tests but as long as we can cover as much with `end to end tests` then IMO we do not need it

2019-03-19 15:24 UTC, sigu submitted a review, later dismissed

2019-03-20 07:15 UTC, sigu approved these changes

2019-03-20 07:16 UTC, merged